spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/rael?useUnicode=true&characterEncoding=utf-8
    username: test_user
    password: haul2
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
   view:
     prefix: /WEB-INF/views/
     suffix: .jsp
  sql:
    init:
      encoding: UTF-8
  security:
    user:
      name: rael
      password: haul2
      roles: ADMIN

  
    
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    jsp:
      init-parameters:
        development: true
  error:
    whitelabel:
      enabled: false
      
logging:
  level:
    org:
      springframework: DEBUG
    com: DEBUG
    
    
    
mybatis:
  type-aliases-package: com.example.rael.dto
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true